name: Deploy Lambda Function

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy to AWS Lambda
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.13  # Ensure compatibility with AWS Lambda

      # Step 3: Install dependencies in a Lambda-compatible way
      - name: Install dependencies
        run: |
          mkdir -p package

          # Install dependencies for AWS Lambda
          pip install \
              --platform manylinux2014_x86_64 \
              --target=package \
              --implementation cp \
              --python-version 3.13 \
              --only-binary=:all: \
              --upgrade -r requirements.txt

          pip install \
              --platform manylinux2014_x86_64 \
              --target=package \
              --implementation cp \
              --python-version 3.13 \
              --only-binary=:all: \
              --upgrade pydantic

          # Ensure chromedriver-autoinstaller is installed
          pip install chromedriver-autoinstaller --target=package

      # Step 4: Install and verify ChromeDriver using `chromedriver-autoinstaller`
      - name: Install ChromeDriver
        run: |
          python -c "import sys; sys.path.append('./package'); import chromedriver_autoinstaller; chromedriver_autoinstaller.install(path='./package')"
          
          # Ensure ChromeDriver exists
          if [ ! -f package/chromedriver ]; then
            echo "❌ ChromeDriver was not installed correctly!"
            exit 1
          fi

      # Step 5: Copy Python scripts & Create deployment ZIP
      - name: Prepare Deployment Package
        run: |
          cp *.py package/

          # Create deployment ZIP
          cd package && zip -r ../index.zip . && cd ..

      # Step 6: Configure AWS credentials
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      # Step 7: Deploy Lambda function
      - name: Deploy Lambda
        run: |
          aws lambda update-function-code \
            --function-name menu-tool-function \
            --zip-file fileb://index.zip
