name: Deploy Lambda Function

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy to AWS Lambda
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.10  # Ensure compatibility with AWS Lambda

      # Step 3: Install dependencies in a Lambda-compatible way
      - name: Install dependencies
        run: |
          mkdir -p package

          # Install Python dependencies with Lambda-compatible settings
          pip install \
              --platform manylinux2014_x86_64 \
              --target=package \
              --implementation cp \
              --python-version 3.10 \
              --only-binary=:all: \
              --upgrade -r requirements.txt

          pip install \
              --platform manylinux2014_x86_64 \
              --target=package \
              --implementation cp \
              --python-version 3.10 \
              --only-binary=:all: \
              --upgrade pydantic

          # Move ChromeDriver into package directory
          mv chromedriver package/

          # Copy Python scripts to package directory
          cp *.py package/

          # Create deployment ZIP
          cd package && zip -r ../index.zip . && cd ..

      # Step 4: Configure AWS credentials
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      # Step 5: Deploy Lambda function
      - name: Deploy Lambda
        run: |
          aws lambda update-function-code \
            --function-name menu-tool-function \
            --zip-file fileb://index.zip
