name: Deploy Lambda Function

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy to AWS Lambda (Python 3.13)
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Python 3.13
      - name: Set up Python 3.13
        uses: actions/setup-python@v4
        with:
          python-version: 3.13  # ✅ AWS Lambda now supports Python 3.13

      # Step 3: Install dependencies in a Lambda-compatible way
      - name: Install dependencies
        run: |
          mkdir -p package

          echo "🔍 Installing dependencies for AWS Lambda (Python 3.13)..."

          pip install \
              --platform manylinux2014_x86_64 \
              --target=package \
              --implementation cp \
              --python-version 3.13 \
              --only-binary=:all: \
              --upgrade -r requirements.txt

          pip install \
              --platform manylinux2014_x86_64 \
              --target=package \
              --implementation cp \
              --python-version 3.13 \
              --only-binary=:all: \
              --upgrade pydantic

          # Ensure chromedriver-autoinstaller is installed and up-to-date
          pip install --upgrade chromedriver-autoinstaller --target=package

      # Step 4: Install and verify ChromeDriver (Fixed for correct copying)
      - name: Install ChromeDriver
        run: |
          echo "🔍 Python Version:"
          python --version  # Ensure Python 3.13 is used

          echo "🔍 Checking Python PATH:"
          python -c "import sys; print(sys.path)"  # Debugging Python path issues

          echo "🔍 Installing ChromeDriver..."
          CHROMEDRIVER_PATH=$(python -c "import sys; sys.path.append('./package'); \
              import chromedriver_autoinstaller; \
              print(chromedriver_autoinstaller.install())")

          echo "✅ ChromeDriver installed at: $CHROMEDRIVER_PATH"

          echo "🔍 Checking ChromeDriver location..."
          find / -name "chromedriver" 2>/dev/null  # Search for all possible locations

          echo "🔍 Validating ChromeDriver installation..."
          if [ -f "$CHROMEDRIVER_PATH" ]; then
            echo "✅ Found ChromeDriver at $CHROMEDRIVER_PATH"
            cp "$CHROMEDRIVER_PATH" package/chromedriver  # Copy instead of move
            chmod +x package/chromedriver
          else
            echo "❌ ChromeDriver path not found! Installation failed."
            exit 1
          fi

          echo "🔍 Verifying package directory contents..."
          ls -l package  # Show contents of package folder

          # Ensure ChromeDriver exists after copying
          if [ -f package/chromedriver ]; then
            echo "✅ ChromeDriver is now in the package directory and ready for Lambda!"
          else
            echo "❌ ChromeDriver was not copied correctly!"
            exit 1
          fi

      # Step 5: Copy Python scripts & Create deployment ZIP
      - name: Prepare Deployment Package
        run: |
          cp *.py package/

          # Create deployment ZIP
          cd package && zip -r ../index.zip . && cd ..

      # Step 6: Configure AWS credentials
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      # Step 7: Deploy Lambda function (Python 3.13)
      - name: Deploy Lambda
        run: |
          aws lambda update-function-code \
            --function-name menu-tool-function \
            --zip-file fileb://index.zip
